### ISSUE TITLE
Unicode support

### ISSUE THREAD

**Issue by machinehead** [ferno/greenery#11]
I've encountered some problems using this library with Russian language. As far as I can see, the problem is in the usage of str's and str literals in code, as well as hardcoding character lists for English. I've managed to make some things work in Py2.7 by adding "from __future__ import unicode_literals" to code and tests, adding Russian to character lists and replacing str to unicode in some places. Maybe I'll come up to a pull request, but in the meantime I'd like to know whether you think it's really needed or you have any ideas on how to implement it the most straightforward way.

**Comment by ferno** [comment]
Python 2 support is being dropped in Greenery 3.0.0+ and Unicode support in Python 3 is pretty excellent, so I consider this issue no longer an issue.
