### ISSUE TITLE
Kleene closure is broken

### ISSUE THREAD

**Issue by edmcman** [ferno/greenery#28]
>>> parse('(ab*)*').to_fsm().accepts('bb')
    True

    >>> parse('(ab*)*').to_fsm()
    fsm(alphabet = set(['a', anything_else, 'b']), states = set([0]), initial = 0, finals = set([0]), map = {0: {'a': 0, 'b': 0}})

**Comment by ferno** [comment]
This is a good spot and definitely a defect, thanks for finding it.
